function drawBest(bestEllipses, image )
if nargin > 1
    imshow(image)
end
hold on
for bestInd = 1:size(bestEllipses)
    iPlot = bestInd; 
    bestCircumference = pi * ( bestEllipses(iPlot,3)+ ...
        bestEllipses(iPlot,4));
    ellipsep(bestEllipses(iPlot,3), ...
            bestEllipses(iPlot,4), ...
            0, ...
            bestEllipses(iPlot,1), ... 
            bestEllipses(iPlot,2), ...
            bestCircumference ); 
end
hold off

